#!/usr/bin/env bash

# Install Homebrew.
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Install and upgrade (by default) all dependencies from the Brewfile.
#
# Read the Brewfile from ~/.Brewfile or the HOMEBREW_BUNDLE_FILE_GLOBAL
# environment variable, if set.
#
# install does not run brew upgrade on outdated dependencies. Note they may
# still be upgraded by brew install if needed.
brew bundle install --global --no-upgrade

# Install Vim plugin manager 'vim-plug'.
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Install Vim plugins.
vim -c PlugInstall -c quitall

# Install useful 'fzf' key bindings and fuzzy completion.
if which brew > /dev/null; then
  "$(brew --prefix fzf)/install" --key-bindings --completion --no-update-rc --no-zsh --no-fish
fi

# Install RVM GPG Keys.
gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

# Install Ruby version manager RVM.
\curl -sSL https://get.rvm.io | bash -s stable

# Install Node.js version manager 'nvm'.
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
