#!/usr/bin/env bash

# Install macOS package manager Homebrew.
if [[ "$(uname)" == "Darwin" ]] && ! which brew > /dev/null; then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Install all dependencies in the global Brewfile.
if which brew > /dev/null; then
  brew bundle install --no-upgrade --global
fi

# Install Vim plugin manager 'vim-plug'.
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Install Vim plugins.
vim -c PlugInstall -c quitall

# Install useful 'fzf' key bindings and fuzzy completion.
if which brew > /dev/null; then
  "$(brew --prefix fzf)/install" --key-bindings --completion --no-update-rc --no-zsh --no-fish
fi

# Install RVM GPG Keys.
gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

# Install Ruby version manager RVM.
\curl -sSL https://get.rvm.io | bash -s stable

# Install Node.js version manager 'nvm'.
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
