#!/usr/bin/env bash

# Execute $HOME/.config/yadm/bootstrap if it exists.
yadm bootstrap

# Update software development environment.
if [[ -f "${HOME}/.bin/update" ]]; then
  "${HOME}/.bin/update"
fi

# Upgrade software development environment.
if [[ -f "${HOME}/.bin/upgrade" ]]; then
  "${HOME}/.bin/upgrade"
fi

# Clean up software development environment.
if [[ -f "${HOME}/.bin/cleanup" ]]; then
  "${HOME}/.bin/cleanup"
fi
