#!/usr/bin/env bash

# Remove stale lock files and outdated downloads for all Homebrew formulae and
# casks, and remove old versions of installed formulae.
if which brew > /dev/null; then
  brew cleanup -s
fi

# Remove unlisted Vim plugins.
vim -c PlugClean -c quitall

# Reclaim all of the space used by RVM archives, repository clones, source files
# (and associated temporary compile file) and logs.
rvm cleanup all
