#!/usr/bin/env bash

# Remove stale lock files and outdated downloads for Homebrew formulae and
# casks, and remove old versions of installed formulae.
brew cleanup -s

# Remove unused Vim plugin directories (bang version will clean without prompt)
vim '+PlugClean' '+quitall'

# Remove unused tmux plugins
"${HOME}/.tmux/plugins/tpm/bin/clean_plugins"

# Reclaim all of the space used by RVM archives, repository clones, source files
# (and associated temporary compile file) and logs
rvm cleanup all
