#!/usr/bin/env bash

# Fetch the newest version of Homebrew and all formulae from GitHub using 'git'
# and perform any necessary migrations.
if which brew > /dev/null; then
  brew update
fi

# Upgrade Vim plugin manager 'vim-plug'.
vim '+PlugUpgrade' '+quitall'
