#!/usr/bin/env bash

# Fetch the newest version of Homebrew and all formulae from GitHub using 'git'
# and perform any necessary migrations.
if which brew > /dev/null; then
  brew update
fi

# Upgrade Vim plugin manager 'vim-plug'.
vim -c PlugUpgrade -c quitall

# Upgrade Vim plugins
vim -c PlugUpdate -c quitall

# Upgrade Ruby version manager RVM.
rvm get stable

# Update Node.js version manager 'nvm'.
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
