#!/usr/bin/env bash

# Fetch the newest version of Homebrew and all formulae from GitHub using git(1)
# and perform any necessary migrations.
brew update

# Upgrade Vim plugin manager 'vim-plug'.
vim -c PlugUpgrade -c quitall

# Upgrade Ruby version manager RVM.
rvm get stable

# Update Node.js version manager 'nvm'.
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
