#!/usr/bin/env bash

# Install and upgrade (by default) all dependencies from the Brewfile.
#
# Read the Brewfile from ~/.Brewfile or the HOMEBREW_BUNDLE_FILE_GLOBAL
# environment variable, if set.
if which brew > /dev/null; then
  brew bundle install --global
fi

# Update Vim plugins.
vim -c PlugUpdate -c quitall
