#!/usr/bin/env bash

alias -- -="cd -"
alias -- ..="cd .."
alias grep="grep --color"
alias egrep="egrep --color"
alias fgrep="fgrep --color"
alias rgrep="rgrep --color"
alias zgrep="zgrep --color"
alias zegrep="zegrep --color"
alias zfgrep="zfgrep --color"
alias g="git"
alias g-="git checkout -"
alias y="yadm"
alias y-="yadm checkout -"
alias b="bundle"
alias be="bundle exec"

if [[ -f "${HOME}/.bashrc.d/aliases.d/ls" ]]; then
  source "${HOME}/.bashrc.d/aliases.d/ls"
fi
