#!/usr/bin/env bash

alias -- -="cd -"
alias -- ..="cd .."
alias ls="ls -FGhlT"
alias la="ls -A"
alias grep="grep --color"
alias egrep="egrep --color"
alias fgrep="fgrep --color"
alias rgrep="rgrep --color"
alias zgrep="zgrep --color"
alias zegrep="zegrep --color"
alias zfgrep="zfgrep --color"
