#!/bin/bash

set -e

# Install Homebrew
if ! which brew > /dev/null; then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi
brew bundle install --no-upgrade --global

# Install submodules
yadm submodule update --init --remote --merge --recursive

# Install Vim Plugin Manager
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim '+PlugInstall' '+quitall'

# Install tmux Plugin Manager
if ! [[ -d "${HOME}/.tmux/plugins/tpm" ]]; then
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi
"${HOME}/.tmux/plugins/tpm/bin/install_plugins"

# Install useful fzf key bindings and fuzzy completion
"$(brew --prefix)/opt/fzf/install" --no-update-rc --no-zsh --no-fish

# Install Ruby Version Manager
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
\curl -sSL https://get.rvm.io | bash

# Install Node.js Version Manager
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
